In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [16]:
df1=pd.read_csv('Multiple_Cause_of_Death_1999-2017.txt',sep='\t',index_col=['County','Year'],nrows=266)

In [22]:
df1.tail(20)

                           Notes  County Code  Year Code      Deaths  \
County               Year
Suffolk County, MA   2017    NaN        25025       2017         230
Worcester County, MA 1999    NaN        25027       1999  Suppressed
                     2000    NaN        25027       2000          10
                     2001    NaN        25027       2001  Suppressed
                     2002    NaN        25027       2002          12
                     2003    NaN        25027       2003          10
                     2004    NaN        25027       2004  Suppressed
                     2005    NaN        25027       2005          14
                     2006    NaN        25027       2006          27
                     2007    NaN        25027       2007          32
                     2008    NaN        25027       2008          29
                     2009    NaN        25027       2009          23
                     2010    NaN        25027       2010          39
                     2011    NaN        25027       2011          50
                     2012    NaN        25027       2012          52
                     2013    NaN        25027       2013          51
                     2014    NaN        25027       2014          84
                     2015    NaN        25027       2015         173
                     2016    NaN        25027       2016         181
                     2017    NaN        25027       2017         228

                           Population  Crude Rate
County               Year
Suffolk County, MA   2017      797939      28.824
Worcester County, MA 1999      744571  Suppressed
                     2000      750963  Unreliable
                     2001      761211  Suppressed
                     2002      768490  Unreliable
                     2003      774476  Unreliable
                     2004      777855  Suppressed
                     2005      781265  Unreliable
                     2006      785345       3.438
                     2007      788280       4.059
                     2008      790847       3.667
                     2009      795251       2.892
                     2010      798552       4.884
                     2011      801227       6.240
                     2012      806163       6.450
                     2013      809106       6.303
                     2014      813475      10.326
                     2015      818963      21.124
                     2016      819589      22.084
                     2017      826116      27.599

In [41]:
after_2005=df1.loc[( 'Suffolk County, MA' , ['2005','2006']),:]

In [49]:
after_2006=df1.xs(2006,level='Year')

In [55]:
after_2008=df1.loc[( slice(None), list(range(2008,2018))  ),:]

In [57]:
after_2008

                            Notes  County Code  Year Code      Deaths  \
County                Year
Barnstable County, MA 2008    NaN        25001       2008  Suppressed
                      2009    NaN        25001       2009  Suppressed
                      2010    NaN        25001       2010          14
                      2011    NaN        25001       2011          18
                      2012    NaN        25001       2012          13
...                           ...          ...        ...         ...
Worcester County, MA  2013    NaN        25027       2013          51
                      2014    NaN        25027       2014          84
                      2015    NaN        25027       2015         173
                      2016    NaN        25027       2016         181
                      2017    NaN        25027       2017         228

                            Population  Crude Rate
County                Year
Barnstable County, MA 2008      217066  Suppressed
                      2009      215994  Suppressed
                      2010      215888  Unreliable
                      2011      215769  Unreliable
                      2012      215423  Unreliable
...                                ...         ...
Worcester County, MA  2013      809106       6.303
                      2014      813475      10.326
                      2015      818963      21.124
                      2016      819589      22.084
                      2017      826116      27.599

[140 rows x 6 columns]